# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e2444edaa5baf2c66ed761b4346461aa0bd3f7c059dad64b56a1c7a0998b6653ebecd11f7af156bf827a010b8b1b4a69e57c77b0c35126302d149e0eea8187a

test:
  secret_key_base: 32eddfa767f48f7d37245aabc6cd418a723baff730e4c0f7ec01dd597a562b21f3d05c87ccd4e110f581a867633c0394072074391c8ae35c75e4486af0edf6aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
